import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({sidebarList}) {
  console.log(sidebarList);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {
          sidebarList?.categories?.map(item => <li key={item._id}>{item.categoryName}</li> )
        }
      </main>
    </div>
  )
}


export async function getStaticProps() {
  const url = `http://18.170.51.237:3000/website/findCategoryAndProducts?isActive=true&storeId=1-2021`;
  const response = await fetch(url);
  const data = await response.json();
  return {
    props: {
      sidebarList: data,
    },
  };
}
